Plat UI 318 - introduce ability to control versions of axe, vnu and chromedriver
hmrc/accessibility-assessment pull request #57
Opened 2021-03-12 15:37 UTC by vivrichards600

2021-03-12 17:59 UTC, ejayaraman requested changes

2021-03-12 17:59 UTC, ejayaraman commented on docker/files/accessibility_tools/README.md
> +### Updating chromedriver
Isn't updating Chromedriver documented in README.md? I am not sure if it fits in this part of README.

2021-03-12 17:59 UTC, ejayaraman commented on docker/Dockerfile
> +      && sudo echo -e '#!/bin/bash\n cd ${HOME}/accessibility_tools \n npx axe "$@"' > /usr/bin/axe \
If there is a way to add an in line Docker comment, we should add a line explaining what is being done here.

2021-03-15 13:38 UTC, vivrichards600 commented on docker/files/accessibility_tools/README.md
> +### Updating chromedriver
Removed in latest commit.

2021-03-15 13:39 UTC, vivrichards600 commented on docker/Dockerfile
> +      && sudo echo -e '#!/bin/bash\n cd ${HOME}/accessibility_tools \n npx axe "$@"' > /usr/bin/axe \
Comment added as discussed which is within the latest commit.

2021-03-16 09:02 UTC, ejayaraman approved these changes

2021-03-16 09:44 UTC, merged